{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Transform File\",\"Transform File (2)\",\"Transform File (3)\",\"vwOccupancyRate\",\"VW_CQCUnratedLocationRatingDtls\",\"vwAgencyCostPercOfTotalCost\",\"Autumn_RMtargets\",\"FactServiceLocationsUnrated\",\"Errors in FactServiceLocationsUnrated\",\"Errors in Autumn_RMtargets\",\"VW_CQCLocationRatingDtls\",\"Errors in Autumn_RMtargets (2)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "    Source = Csv.Document(Parameter1,[Delimiter=\",\", Columns=102, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "80a52229-5ee0-4050-9f65-22d69d76a7a8",
        "queryGroup": "Transform File from AP Data\\Helper Queries"
      },
      {
        "name": "Transform File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter2 as binary) => let",
          "    Source = Csv.Document(Parameter2,[Delimiter=\",\", Columns=102, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "eadb7f38-d2ab-41c0-a17c-ab3db7187f29",
        "queryGroup": "Transform File from Query1\\Helper Queries"
      },
      {
        "name": "Transform File (3)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter3 as binary) => let",
          "    Source = Csv.Document(Parameter3,[Delimiter=\",\", Columns=102, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "728391dd-531a-4662-96f0-e66a3afac428",
        "queryGroup": "Transform File from Query3\\Helper Queries"
      },
      {
        "name": "Errors in FactServiceLocationsUnrated",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "Source = FactServiceLocationsUnrated,",
          "  #\"Detected Type Mismatches\" = let",
          "    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Source, Table.ColumnsOfType(Source, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),",
          "    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),",
          "    fieldNames = Record.FieldNames(recordTypeFields),",
          "    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),",
          "    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = \"The type of the value does not match the type of the column.\", Detail = v], fieldTypes{i}})",
          "in",
          "    Table.TransformColumns(Source, pairs),",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Detected Type Mismatches\", \"Row Number\" ,1),",
          "  #\"Kept Errors\" = Table.SelectRowsWithErrors(#\"Added Index\", {\"Location ID\", \"Dormant (Y/N)\", \"Care home?\", \"Location Name\", \"Location ODS Code\", \"Location Telephone Number\", \"Registered manager \", \"Location Web Address\", \"Care homes beds\", \"Location Type/Sector\", \"Location Inspection Directorate\", \"Location Primary Inspection Category\", \"Location Latest Overall Rating\", \"Publication Date\", \"Inherited Rating (Y/N)\", \"Location Region\", \"Location NHS Region\", \"Location Local Authority\", \"Location ONSPD CCG Code\", \"Location ONSPD CCG\", \"Location Commissioning CCG Code\", \"Location Commissioning CCG\", \"Location Street Address\", \"Location Address Line 2\", \"Location City\", \"Location County\", \"Location Postal Code\", \"Location PAF ID\", \"Location UPRN ID\", \"Location Latitude\", \"Location Longitude\", \"Location Parliamentary Constituency\", \"Brand ID\", \"Brand Name\", \"Provider Companies House Number\", \"Provider Charity Number\", \"Provider ID\", \"Provider Name\", \"Provider HSCA start date\", \"Provider Type/Sector\", \"Provider Inspection Directorate\", \"Provider Primary Inspection Category\", \"Provider Ownership Type\", \"Provider Telephone Number\", \"Provider Web Address\", \"Provider Street Address\", \"Provider Address Line 2\", \"Provider City\", \"Provider County\", \"Provider Postal Code\", \"Provider PAF ID\", \"Provider UPRN ID\", \"Provider Local Authority\", \"Provider Region\", \"Provider NHS Region\", \"Provider Latitude\", \"Provider Longitude\", \"Provider Parliamentary Constituency\", \"Provider Nominated Individual Name\", \"Provider Main Partner Name\", \"Regulated activity - Accommodation for persons who require nursing or personal care\", \"Regulated activity - Accommodation for persons who require treatment for substance misuse\", \"Regulated activity - Assessment or medical treatment for persons detained under the Mental Health Act 1983\", \"Regulated activity - Diagnostic and screening procedures\", \"Regulated activity - Family planning\", \"Regulated activity - Management of supply of blood and blood derived products\", \"Regulated activity - Maternity and midwifery services\", \"Regulated activity - Nursing care\", \"Regulated activity - Personal care\", \"Regulated activity - Services in slimming clinics\", \"Regulated activity - Surgical procedures\", \"Regulated activity - Termination of pregnancies\", \"Regulated activity - Transport services, triage and medical advice provided remotely\", \"Regulated activity - Treatment of disease, disorder or injury\", \"Service type - Acute services with overnight beds\", \"Service type - Acute services without overnight beds / listed acute services with or without overnight beds\", \"Service type - Ambulance service\", \"Service type - Blood and Transplant service\", \"Service type - Care home service with nursing\", \"Service type - Care home service without nursing\", \"Service type - Community based services for people who misuse substances\", \"Service type - Community based services for people with a learning disability\", \"Service type - Community based services for people with mental health needs\", \"Service type - Community health care services - Nurses Agency only\", \"Service type - Community healthcare service\", \"Service type - Dental service\", \"Service type - Diagnostic and/or screening service\", \"Service type - Diagnostic and/or screening service - single handed sessional providers\", \"Service type - Doctors consultation service\", \"Service type - Doctors treatment service\", \"Service type - Domiciliary care service\", \"Service type - Extra Care housing services\", \"Service type - Hospice services\", \"Service type - Hospice services at home\", \"Service type - Hospital services for people with mental health needs, learning disabilities and problems with substance misuse\", \"Service type - Hyperbaric Chamber\", \"Service type - Long term conditions services\", \"Service type - Mobile doctors service\", \"Service type - Prison Healthcare Services\", \"Service type - Rehabilitation services\", \"Service type - Remote clinical advice service\", \"Service type - Residential substance misuse treatment and/or rehabilitation service\", \"Service type - Shared Lives\", \"Service type - Specialist college service\", \"Service type - Supported living service\", \"Service type - Urgent care services\", \"Service user band - Children 0-18 years\", \"Service user band - Dementia\", \"Service user band - Learning disabilities or autistic spectrum disorder\", \"Service user band - Mental Health\", \"Service user band - Older People\", \"Service user band - People detained under the Mental Health Act\", \"Service user band - People who misuse drugs and alcohol\", \"Service user band - People with an eating disorder\", \"Service user band - Physical Disability\", \"Service user band - Sensory Impairment\", \"Service user band - Whole Population\", \"Service user band - Younger Adults\", \"Fiscal_Month\", \"SourceFileName\", \"Publication_Date\", \"Calculated rating\"}),",
          "  #\"Reordered Columns\" = Table.ReorderColumns(#\"Kept Errors\", {\"Row Number\", \"Location ID\", \"Dormant (Y/N)\", \"Care home?\", \"Location Name\", \"Location ODS Code\", \"Location Telephone Number\", \"Registered manager \", \"Location Web Address\", \"Care homes beds\", \"Location Type/Sector\", \"Location Inspection Directorate\", \"Location Primary Inspection Category\", \"Location Latest Overall Rating\", \"Publication Date\", \"Inherited Rating (Y/N)\", \"Location Region\", \"Location NHS Region\", \"Location Local Authority\", \"Location ONSPD CCG Code\", \"Location ONSPD CCG\", \"Location Commissioning CCG Code\", \"Location Commissioning CCG\", \"Location Street Address\", \"Location Address Line 2\", \"Location City\", \"Location County\", \"Location Postal Code\", \"Location PAF ID\", \"Location UPRN ID\", \"Location Latitude\", \"Location Longitude\", \"Location Parliamentary Constituency\", \"Brand ID\", \"Brand Name\", \"Provider Companies House Number\", \"Provider Charity Number\", \"Provider ID\", \"Provider Name\", \"Provider HSCA start date\", \"Provider Type/Sector\", \"Provider Inspection Directorate\", \"Provider Primary Inspection Category\", \"Provider Ownership Type\", \"Provider Telephone Number\", \"Provider Web Address\", \"Provider Street Address\", \"Provider Address Line 2\", \"Provider City\", \"Provider County\", \"Provider Postal Code\", \"Provider PAF ID\", \"Provider UPRN ID\", \"Provider Local Authority\", \"Provider Region\", \"Provider NHS Region\", \"Provider Latitude\", \"Provider Longitude\", \"Provider Parliamentary Constituency\", \"Provider Nominated Individual Name\", \"Provider Main Partner Name\", \"Regulated activity - Accommodation for persons who require nursing or personal care\", \"Regulated activity - Accommodation for persons who require treatment for substance misuse\", \"Regulated activity - Assessment or medical treatment for persons detained under the Mental Health Act 1983\", \"Regulated activity - Diagnostic and screening procedures\", \"Regulated activity - Family planning\", \"Regulated activity - Management of supply of blood and blood derived products\", \"Regulated activity - Maternity and midwifery services\", \"Regulated activity - Nursing care\", \"Regulated activity - Personal care\", \"Regulated activity - Services in slimming clinics\", \"Regulated activity - Surgical procedures\", \"Regulated activity - Termination of pregnancies\", \"Regulated activity - Transport services, triage and medical advice provided remotely\", \"Regulated activity - Treatment of disease, disorder or injury\", \"Service type - Acute services with overnight beds\", \"Service type - Acute services without overnight beds / listed acute services with or without overnight beds\", \"Service type - Ambulance service\", \"Service type - Blood and Transplant service\", \"Service type - Care home service with nursing\", \"Service type - Care home service without nursing\", \"Service type - Community based services for people who misuse substances\", \"Service type - Community based services for people with a learning disability\", \"Service type - Community based services for people with mental health needs\", \"Service type - Community health care services - Nurses Agency only\", \"Service type - Community healthcare service\", \"Service type - Dental service\", \"Service type - Diagnostic and/or screening service\", \"Service type - Diagnostic and/or screening service - single handed sessional providers\", \"Service type - Doctors consultation service\", \"Service type - Doctors treatment service\", \"Service type - Domiciliary care service\", \"Service type - Extra Care housing services\", \"Service type - Hospice services\", \"Service type - Hospice services at home\", \"Service type - Hospital services for people with mental health needs, learning disabilities and problems with substance misuse\", \"Service type - Hyperbaric Chamber\", \"Service type - Long term conditions services\", \"Service type - Mobile doctors service\", \"Service type - Prison Healthcare Services\", \"Service type - Rehabilitation services\", \"Service type - Remote clinical advice service\", \"Service type - Residential substance misuse treatment and/or rehabilitation service\", \"Service type - Shared Lives\", \"Service type - Specialist college service\", \"Service type - Supported living service\", \"Service type - Urgent care services\", \"Service user band - Children 0-18 years\", \"Service user band - Dementia\", \"Service user band - Learning disabilities or autistic spectrum disorder\", \"Service user band - Mental Health\", \"Service user band - Older People\", \"Service user band - People detained under the Mental Health Act\", \"Service user band - People who misuse drugs and alcohol\", \"Service user band - People with an eating disorder\", \"Service user band - Physical Disability\", \"Service user band - Sensory Impairment\", \"Service user band - Whole Population\", \"Service user band - Younger Adults\", \"Fiscal_Month\", \"SourceFileName\", \"Publication_Date\", \"Calculated rating\"})",
          "in",
          "  #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "abbc18ce-1fa8-4741-b158-221666682141",
        "queryGroup": "Query Errors - 2/28/2023 5:14:08 PM"
      },
      {
        "name": "Errors in Autumn_RMtargets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "Source = Autumn_RMtargets,",
          "  #\"Detected Type Mismatches\" = let",
          "    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Source, Table.ColumnsOfType(Source, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),",
          "    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),",
          "    fieldNames = Record.FieldNames(recordTypeFields),",
          "    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),",
          "    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = \"The type of the value does not match the type of the column.\", Detail = v], fieldTypes{i}})",
          "in",
          "    Table.TransformColumns(Source, pairs),",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Detected Type Mismatches\", \"Row Number\" ,1),",
          "  #\"Kept Errors\" = Table.SelectRowsWithErrors(#\"Added Index\", {\"Head Of Operations\", \"Regional Manager\", \"Measure\", \"FiscalYear\", \"Month Name\", \"Value\"}),",
          "  #\"Reordered Columns\" = Table.ReorderColumns(#\"Kept Errors\", {\"Row Number\", \"Head Of Operations\", \"Regional Manager\", \"Measure\", \"FiscalYear\", \"Month Name\", \"Value\"})",
          "in",
          "  #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "3db322fe-b822-4a45-a4df-eb52ddfcfb6c",
        "queryGroup": "Query Errors - 3/7/2023 11:52:54 AM"
      },
      {
        "name": "Errors in Autumn_RMtargets (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "Source = Autumn_RMtargets,",
          "  #\"Detected Type Mismatches\" = let",
          "    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Source, Table.ColumnsOfType(Source, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),",
          "    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),",
          "    fieldNames = Record.FieldNames(recordTypeFields),",
          "    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),",
          "    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = \"The type of the value does not match the type of the column.\", Detail = v], fieldTypes{i}})",
          "in",
          "    Table.TransformColumns(Source, pairs),",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Detected Type Mismatches\", \"Row Number\" ,1),",
          "  #\"Kept Errors\" = Table.SelectRowsWithErrors(#\"Added Index\", {\"Head Of Operations\", \"Regional Manager\", \"Measure\", \"FiscalYear\", \"Region\", \"Month Name\", \"Value\"}),",
          "  #\"Reordered Columns\" = Table.ReorderColumns(#\"Kept Errors\", {\"Row Number\", \"Head Of Operations\", \"Regional Manager\", \"Measure\", \"FiscalYear\", \"Region\", \"Month Name\", \"Value\"})",
          "in",
          "  #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "68c9ca9f-8467-4789-bdc5-b4c3b707138b",
        "queryGroup": "Query Errors - 20-03-2023 19:15:19"
      },
      {
        "name": "FactServiceLocationsUnrated",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"sqlminstanceatprod.public.6ebcd2a481ea.database.windows.net, 3342\", \"ATDMP\", [Query=\"select 12-12\"])",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "837b4438-d5d2-48c3-80e5-0a16fb1af1de"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from AP Data"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from AP Data\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Transform File from Query1"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Query1\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Transform File from Query3"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Query3\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ],
        "description": "Errors in queries that were loaded on 2/28/2023 5:14:08 PM.",
        "folder": "Query Errors - 2/28/2023 5:14:08 PM"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "7"
          }
        ],
        "description": "Errors in queries that were loaded on 3/7/2023 11:52:54 AM.",
        "folder": "Query Errors - 3/7/2023 11:52:54 AM"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "8"
          }
        ],
        "description": "Errors in queries that were loaded on 20-03-2023 19:15:19.",
        "folder": "Query Errors - 20-03-2023 19:15:19"
      }
    ],
    "relationships": [
      {
        "name": "96f743e0-5707-4efb-ba85-015f1aada8b5",
        "fromColumn": "Empty_Dt",
        "fromTable": "vwOccupancyRate",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_83d935b1-9980-4b2a-9f55-8be80245df33"
      },
      {
        "name": "9aa9bcf6-f059-4781-9468-f5fb6ad98ed0",
        "fromColumn": "Publication_Date",
        "fromTable": "VW_CQCLocationRatingDtls",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_62cae5d2-bf80-4cb7-ac76-c0cb73bfc310"
      },
      {
        "name": "db832b54-3acf-475c-ae7f-788eb7ce2d1f",
        "fromColumn": "DraftReportDate",
        "fromTable": "VW_CQCLocationRatingDtls",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_639f3697-e557-4885-bea0-cff7367d1e93"
      },
      {
        "name": "b105cdca-b088-4e95-9851-2b72b7aa1dff",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "FiscalMonthYear",
        "fromTable": "DatesTable",
        "toCardinality": "many",
        "toColumn": "FiscalYearMonthNo",
        "toTable": "Autumn_RMtargets"
      },
      {
        "name": "21ef465e-6455-41c6-84a1-b577f0bcfa52",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "hoa_reg_fm",
        "fromTable": "Autumn_RMtargets",
        "toCardinality": "many",
        "toColumn": "hoa_reg_fm",
        "toTable": "vwAgencyCostPercOfTotalCost"
      },
      {
        "name": "3fa3233c-f0e7-429d-9bbc-41f8175da135",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "hoa_reg_fm",
        "fromTable": "Autumn_RMtargets",
        "toCardinality": "many",
        "toColumn": "hoa_reg_fm",
        "toTable": "vwOccupancyRate"
      },
      {
        "name": "0387ef75-fc53-4eb8-8bf9-4169b3df5752",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "hoa_reg_fm",
        "fromTable": "Autumn_RMtargets",
        "toCardinality": "many",
        "toColumn": "hoa_reg_fm",
        "toTable": "VW_CQCLocationRatingDtls"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "DateTableTemplate_2ef0ec50-e8fd-475a-831e-d2d48632aa9d",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7f949571-bc00-4837-9a60-d72850a7f3eb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a234f25d-e9e1-465d-954a-75c6a984ceb2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f2840eff-be5d-4901-bda5-c1fa676ed96a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b4b69614-2705-4e43-9798-2398f73edf9a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2d93e35e-f618-4702-84e0-d7e79d8e1d06",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "07dfada7-ee79-4305-b9ee-a8c5ba546dc2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "da4a8735-94e1-4e2f-819b-827b170df516",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a186bd59-7570-4831-acd9-87abcaa6c168",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0d1de8dd-75b6-4bdf-a572-01502442e1d5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "00cace4c-1b42-49f3-b0e0-e062c8f0de27",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "341dfeb9-fd09-481a-8204-4137c93cb108",
                "ordinal": 3
              }
            ],
            "lineageTag": "aa1df9ea-09dc-40e1-9671-d70e854301f9"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "2cdc0557-3acd-49ef-acf4-969a9c3b66e2",
        "partitions": [
          {
            "name": "DateTableTemplate_2ef0ec50-e8fd-475a-831e-d2d48632aa9d-413a1004-b1fc-415a-b10b-16171903d160",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "vwOccupancyRate",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Head of Operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0254872-4148-4477-b970-017ea6e552fc",
            "sourceColumn": "Head of Operations",
            "summarizeBy": "none"
          },
          {
            "name": "Regional Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3488b6a6-387c-4e06-9700-5765436fce35",
            "sourceColumn": "Regional Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Cost Centre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcf72baf-5f98-4806-8662-d4445a0efd71",
            "sourceColumn": "Cost Centre",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarYearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "11ec5877-bcb9-4ef5-b535-b513c05ca745",
            "sourceColumn": "CalendarYearMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal_Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bc7eeec2-2297-41aa-93a7-60d57cd53d9a",
            "sourceColumn": "Fiscal_Month",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalRoomCnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "48b62c23-3607-47ee-a5b2-03c53f0a8c43",
            "sourceColumn": "TotalRoomCnt",
            "summarizeBy": "sum"
          },
          {
            "name": "Fclty_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b406fb41-6763-4f25-9590-4231d224e703",
            "sourceColumn": "Fclty_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Srvc_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c10bade-778b-4a59-9a7a-e94507915999",
            "sourceColumn": "Srvc_Name",
            "summarizeBy": "none"
          },
          {
            "name": "RoomStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bb0029c7-b846-4d8c-ae95-bf3cb1d33a58",
            "sourceColumn": "RoomStatus",
            "summarizeBy": "sum"
          },
          {
            "name": "snapshotcapturedate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a384855-6920-4758-89d0-0fd2dd8f221b",
            "sourceColumn": "snapshotcapturedate",
            "summarizeBy": "none"
          },
          {
            "name": "OccuRatePct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "lineageTag": "ad887af3-f3dd-4185-9206-abb9cfceb572",
            "sourceColumn": "OccuRatePct",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2893000f-59b1-498f-87da-340563157f75",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarYearMonth - Copy.2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec44068a-c00c-4c4d-bc5b-00c1fb6c84e7",
            "sourceColumn": "CalendarYearMonth - Copy.2",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "SWITCH([CalendarYearMonth - Copy.2], 1, \"January\", 2, \"February\", 3, \"March\", 4, \"April\", 5, \"May\", 6, \"June\", 7, \"July\", 8, \"August\", 9, \"September\", 10, \"October\", 11, \"November\", 12, \"December\", \"Invalid Month\")",
            "isDataTypeInferred": true,
            "lineageTag": "41aa231a-3c38-4721-aeac-79554ffabb97",
            "sortByColumn": "CalendarYearMonth",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Empty_Dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "86b46d14-f70a-4d8a-9802-394bbe1df5f8",
            "sourceColumn": "Empty_Dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_83d935b1-9980-4b2a-9f55-8be80245df33"
                },
                "isDefault": true,
                "relationship": "96f743e0-5707-4efb-ba85-015f1aada8b5"
              }
            ]
          },
          {
            "name": "hoa_rm_fm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(vwOccupancyRate[Head of Operations],vwOccupancyRate[Regional Manager]) ,vwOccupancyRate[Fiscal_Month])",
            "isDataTypeInferred": true,
            "lineageTag": "c10ecbfa-dea1-46cd-8132-bda87b255d13",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Service Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db44f201-c810-4635-9647-e1f0f36b173e",
            "sourceColumn": "Service Status",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ceb1acb-56b8-41d8-8db3-221365fa7e32",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "hoa_reg_fm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(vwOccupancyRate[Head of Operations],vwOccupancyRate[Region]) ,vwOccupancyRate[Fiscal_Month])",
            "isDataTypeInferred": true,
            "lineageTag": "5052d4fd-c9e6-4d92-be0f-35fe14645c67",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "EmptySinceDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46737357-ef5b-487a-9d3d-033973184c7d",
            "sourceColumn": "EmptySinceDays",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "243af113-6de9-4674-a002-44fc7d9f0b21",
        "measures": [
          {
            "name": "Occupancy Rate PCT",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM(vwOccupancyRate[OccuRatePct]),FILTER(vwOccupancyRate,vwOccupancyRate[snapshotcapturedate]=MAX(vwOccupancyRate[snapshotcapturedate])))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "981436c2-d778-4ca0-b85a-efe1e4f1ac82"
          },
          {
            "name": "Occupancy %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(vwOccupancyRate[OccuRatePct])",
            "lineageTag": "8d8924e1-20ae-421e-9281-6c270eb7be85"
          },
          {
            "name": "Occupancy_Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),Autumn_RMtargets,Autumn_RMtargets[Measure]=\"occupancy\")",
            "lineageTag": "e52a24b5-0fe1-4e2e-9dc8-2f9363bdbfee"
          },
          {
            "name": "AvgOccupany",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(vwOccupancyRate[OccuRatePct])",
            "lineageTag": "5528a052-3e78-4aa3-ac2c-3fef57a757a2"
          },
          {
            "name": "occupancytarget",
            "expression": [
              "",
              "IF ( [AvgOccupany] >[Occupancy_Target],0,1)"
            ],
            "formatString": "0",
            "lineageTag": "bc3284cd-e539-4455-a6b9-5aed4b8b1ce3"
          },
          {
            "name": "Flag Occupancy",
            "expression": "IF(ISBLANK([Max Occupancy]),2,IF([Max Occupancy]>[AvgOccupancy],0,1))",
            "formatString": "0",
            "lineageTag": "8ac5371b-0605-40c5-b305-119433a2c0df"
          },
          {
            "name": "Max Occupancy",
            "expression": [
              "var act = CALCULATE(SUM(vwOccupancyRate[RoomStatus]))",
              "",
              "return IF(ISBLANK(act),0,act)"
            ],
            "formatString": "0",
            "lineageTag": "28bc8f1a-0b9d-4033-8eeb-eb0c0f256d38"
          },
          {
            "name": "Occupancy_chart",
            "expression": "CALCULATE(SUM(vwOccupancyRate[RoomStatus]))",
            "formatString": "0",
            "lineageTag": "94d7a6d2-2cdf-4ae1-a223-0497072d934c"
          }
        ],
        "partitions": [
          {
            "name": "vwOccupancyRate-3c636466-4118-4400-85c8-f3b2003c23c3",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqlminstanceatprod.public.6ebcd2a481ea.database.windows.net,3342\", \"ATDMP\"),",
                "    dbo_vwOccupancyRate = Source{[Schema=\"dbo\",Item=\"vwOccupancyRate\"]}[Data],",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(dbo_vwOccupancyRate, \"CalendarYearMonth\", \"CalendarYearMonth - Copy\"),",
                "    #\"Split Column by Position\" = Table.SplitColumn(Table.TransformColumnTypes(#\"Duplicated Column\", {{\"CalendarYearMonth - Copy\", type text}}, \"en-US\"), \"CalendarYearMonth - Copy\", Splitter.SplitTextByRepeatedLengths(4), {\"CalendarYearMonth - Copy.1\", \"CalendarYearMonth - Copy.2\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Split Column by Position\",{{\"CalendarYearMonth - Copy.2\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"CalendarYearMonth - Copy.1\", \"Year\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"Dean Thomas-Bines (he/him)\",\"Dean Thomas-Bines\",Replacer.ReplaceText,{\"Head of Operations\"})",
                "in",
                "    #\"Replaced Value\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VW_CQCUnratedLocationRatingDtls",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Head_Of_Operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b16e4e11-787a-4301-ae60-81569d8acf46",
            "sourceColumn": "Head_Of_Operations",
            "summarizeBy": "none"
          },
          {
            "name": "Cost Centre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7dc8ecb-c3f4-4e59-8d50-d1ad4c85ec17",
            "sourceColumn": "Cost Centre",
            "summarizeBy": "none"
          },
          {
            "name": "Regional Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3362910-f574-44e8-a735-64fdeb861c59",
            "sourceColumn": "Regional Manager",
            "summarizeBy": "none"
          },
          {
            "name": "LocationLatestOverallRating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4287f2fe-65ba-4928-8735-a103e5ba3ed1",
            "sourceColumn": "LocationLatestOverallRating",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal_Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93dc8709-2487-4a9f-ac3a-56d051551ca8",
            "sourceColumn": "Fiscal_Month",
            "summarizeBy": "none"
          },
          {
            "name": "ServiceRatingCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "378c2ce0-3a7f-411e-9095-c28a0a3ac845",
            "sourceColumn": "ServiceRatingCount",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalService",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49a17acf-efd3-47aa-b6c3-44baca5696d5",
            "sourceColumn": "TotalService",
            "summarizeBy": "sum"
          },
          {
            "name": "Facility Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f5fe9c4-1b25-4985-9943-d21e8426add6",
            "sourceColumn": "Facility Code",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38dde061-1e67-4766-b0f5-2a8b28ae3098",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Latest_Audit_Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "727b95d8-6391-46b4-834f-d86c42485fad",
            "sourceColumn": "Latest_Audit_Rating",
            "summarizeBy": "none"
          },
          {
            "name": "Overdue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a8d0321-daff-43e9-a828-8c2196c77eaa",
            "sourceColumn": "Overdue",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a5b47cd0-dfd2-4281-a5c4-76af49244d0d",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month No.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8bd29727-b312-4505-b04e-fdac60dec92f",
            "sourceColumn": "Month No.",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "SWITCH([Month No.], 1, \"March\", 2, \"April\", 3, \"May\", 4, \"June\", 5, \"July\", 6, \"August\", 7, \"September\", 8, \"October\", 9, \"November\", 10, \"December\", 11, \"January\", 12, \"February\", \"Invalid Month\")",
            "isDataTypeInferred": true,
            "lineageTag": "cfaac57d-1171-4cb5-b585-22f1c68d7f61",
            "sortByColumn": "Month No.",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dean",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF(VW_CQCUnratedLocationRatingDtls[Head_Of_Operations]=\"Dean Thomas-Bines\",1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "16e69617-5595-46f4-9fd6-7792a7482005",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Regulator ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c83ed10-7bf7-402e-95bc-33105d47b1ca",
            "sourceColumn": "Regulator ID",
            "summarizeBy": "none"
          },
          {
            "name": "Regulator Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df23bf1e-96f9-41be-9ee1-bee1c470b177",
            "sourceColumn": "Regulator Name",
            "summarizeBy": "none"
          },
          {
            "name": "cqcLocationLatestOverallRating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "807bb9b7-9cbe-4c33-819e-3f81ec031969",
            "sourceColumn": "cqcLocationLatestOverallRating",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7728877a-315f-4e0f-832f-26c3f76ed266",
        "measures": [
          {
            "name": "Quality",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var act = CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),FILTER(VW_CQCLocationRatingDtls,VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"Good\"))",
              "",
              "return IF(ISBLANK(act),0,act)"
            ],
            "formatString": "0",
            "lineageTag": "8cc461b1-19e2-4873-aa59-d17c0a74ec0c"
          },
          {
            "name": "Good",
            "expression": [
              "CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),FILTER(VW_CQCLocationRatingDtls,VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"Good\"))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "dc880baa-dfee-4aea-a5fd-6eea6c63420d"
          },
          {
            "name": "RI",
            "expression": [
              "CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),FILTER(VW_CQCLocationRatingDtls,VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"Requires Improvement\"))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "97a63cb7-22a9-40f6-b82c-9549c4cfe2f0"
          },
          {
            "name": "Outstanding",
            "expression": [
              "",
              "",
              "var act = CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),FILTER(VW_CQCLocationRatingDtls,VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"outstanding\"))",
              "",
              "return IF(ISBLANK(act), 0,act)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "4a641925-1397-4276-809f-84b1b963545a"
          },
          {
            "name": "Inadequate",
            "expression": [
              "CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),FILTER(VW_CQCLocationRatingDtls,VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"inadequate\"))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "afc3245f-b09c-4e2e-a4da-5a958646f168"
          },
          {
            "name": "Inadequate %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var act = CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),FILTER(VW_CQCLocationRatingDtls,VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"Inadequate\"))",
              "",
              "",
              "return IF(ISBLANK(act),0,act)"
            ],
            "formatString": "0",
            "lineageTag": "279e1b1d-210b-4e1a-bd31-b64d2af30d35"
          },
          {
            "name": "RI %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var act  = CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"Requires Improvement\")",
              "return IF(ISBLANK(act),0,act)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "4c3067d1-442b-42ff-b1fa-f19ddb311126"
          },
          {
            "name": "Good target",
            "expression": [
              "",
              "IF ( [Quality] >[Good_Target],0,1)"
            ],
            "formatString": "0",
            "lineageTag": "21279c41-4d7b-4596-b9d7-d77dbd926d28"
          },
          {
            "name": "Good_Target",
            "expression": "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),Autumn_RMtargets,Autumn_RMtargets[Measure]=\"Quality-Good\",Autumn_RMtargets[Regional Manager]<>\"rm\")",
            "formatString": "0",
            "lineageTag": "4a0f4ad0-e8da-4f18-9049-97b2d2651d7d"
          },
          {
            "name": "RI_Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),Autumn_RMtargets,Autumn_RMtargets[Measure]=\"Quality-RI\",Autumn_RMtargets[Regional Manager]<>\"rm\")",
            "lineageTag": "2073f0aa-070f-40d7-b727-aef1b69fa956"
          },
          {
            "name": "RI Target",
            "expression": "IF ( [RI %] >[RI_Target],0,1)",
            "formatString": "0",
            "lineageTag": "87161606-1a59-4da9-97c1-d8469cf92a41"
          },
          {
            "name": "Flag RI Rm",
            "expression": "IF([RI %]>[RI_Target],0,1)",
            "formatString": "0",
            "lineageTag": "49d30afb-fae6-480c-91f4-fb8f26b531b9"
          },
          {
            "name": "Measure 3",
            "expression": "IF([Inadequate %]>[IN_Target],0,1)",
            "formatString": "0",
            "lineageTag": "57378558-e903-49d4-9cad-d72306feeba5"
          },
          {
            "name": "Measure 5",
            "expression": [
              "var a= CALCULATE(DISTINCTCOUNT(VW_CQCUnratedLocationRatingDtls[Regulator ID]),FILTER(VW_CQCUnratedLocationRatingDtls,VW_CQCUnratedLocationRatingDtls[LocationLatestOverallRating]=\"Good\"))",
              "",
              "var b=DISTINCTCOUNT(VW_CQCUnratedLocationRatingDtls[Regulator ID])",
              "",
              "return a/b"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1c4d692b-7aa1-479f-81b2-832c5d688063"
          },
          {
            "name": "RI%_countx",
            "expression": [
              "",
              "",
              "",
              "IF(",
              "ISFILTERED(VW_CQCLocationRatingDtls[Regional Manager]),",
              "DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),",
              "COUNTX(VW_CQCLocationRatingDtls, VW_CQCLocationRatingDtls[Regulator ID])",
              "",
              ")",
              "--var a = SELECTEDVALUE(VW_CQCLocationRatingDtls[Manual_Override_ratings])",
              "--var b = DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID])",
              "",
              "--return SWITCH(a,\"Requires improvement\",b)",
              "",
              "",
              "   --COUNTX(  SUMMARIZE ( VW_CQCLocationRatingDtls, VW_CQCLocationRatingDtls[Head of Operations], VW_CQCLocationRatingDtls[Regional Manager], VW_CQCLocationRatingDtls[Fiscal_Month]),VALUES(VW_CQCLocationRatingDtls[Regulator ID]))"
            ],
            "formatString": "0",
            "lineageTag": "9c05e03b-4af8-428e-ad47-6309d3115b13"
          },
          {
            "name": "RI%_Chart",
            "expression": [
              "",
              "",
              "var act  = CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"Requires Improvement\")",
              "return act"
            ],
            "formatString": "0",
            "lineageTag": "1a725604-3231-40fd-a9c5-7dc0431ffbb6"
          },
          {
            "name": "Inadequate%_chart",
            "expression": [
              "",
              "",
              "var act = CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),FILTER(VW_CQCLocationRatingDtls,VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"Inadequate\"))",
              "",
              "",
              "return act"
            ],
            "formatString": "0",
            "lineageTag": "53d43841-cb06-445e-ba75-823620fb6922"
          }
        ],
        "partitions": [
          {
            "name": "VW_CQCUnratedLocationRatingDtls-2a25a765-a1a8-4ab6-b1b8-9b65c9cf115e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqlminstanceatprod.public.6ebcd2a481ea.database.windows.net,3342\", \"ATDMP\"),",
                "    dbo_VW_CQCUnratedLocationRatingDtls = Source{[Schema=\"dbo\",Item=\"VW_CQCUnratedLocationRatingDtls\"]}[Data],",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(dbo_VW_CQCUnratedLocationRatingDtls, \"Fiscal_Month\", \"Fiscal_Month - Copy\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"Fiscal_Month - Copy\", \"Year\"}}),",
                "    #\"Split Column by Position\" = Table.SplitColumn(#\"Renamed Columns\", \"Year\", Splitter.SplitTextByRepeatedLengths(4), {\"Year.1\", \"Year.2\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Split Column by Position\",{{\"Year.1\", Int64.Type}, {\"Year.2\", Int64.Type}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\",{{\"Year.1\", \"Year\"}, {\"Year.2\", \"Month No.\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns1\",null,\"Unrated\",Replacer.ReplaceValue,{\"LocationLatestOverallRating\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Replaced Value\", each true)",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "vwAgencyCostPercOfTotalCost",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Head of Operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04c069c7-558f-4b5c-bbd6-c40628e12e4e",
            "sourceColumn": "Head of Operations",
            "summarizeBy": "none"
          },
          {
            "name": "Regional Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c6ed310-1e7e-4106-981c-9bfa977ce8a2",
            "sourceColumn": "Regional Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Cost Centre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1924b4b1-e7e7-4757-818b-8d5fd5a272e5",
            "sourceColumn": "Cost Centre",
            "summarizeBy": "none"
          },
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "39cac275-6940-4d33-b162-11cc1c7a0f10",
            "sourceColumn": "Period",
            "summarizeBy": "sum"
          },
          {
            "name": "CostCentre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ddb4ca1f-3b81-4d5a-82e7-c8b65f689273",
            "sourceColumn": "CostCentre",
            "summarizeBy": "sum"
          },
          {
            "name": "StaffCost_Monthly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "81957987-4804-4ac2-8987-cdeb6406a492",
            "sourceColumn": "StaffCost_Monthly",
            "summarizeBy": "sum"
          },
          {
            "name": "AgencyCost_Excl_Premium_Monthly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ef49bb4b-0235-48c9-b1e3-21ede5672487",
            "sourceColumn": "AgencyCost_Excl_Premium_Monthly",
            "summarizeBy": "sum"
          },
          {
            "name": "AgencyCost_Monthly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "12b8b01c-dd4f-4fc9-99bc-7ac68ccd3a43",
            "sourceColumn": "AgencyCost_Monthly",
            "summarizeBy": "sum"
          },
          {
            "name": "AgencyCostPercOfTotalCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "lineageTag": "77f39964-ca2a-4529-b252-6fd97369a470",
            "sourceColumn": "AgencyCostPercOfTotalCost",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "37b96365-0866-44bc-adec-2e093e3c0a84",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month No.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3896ba7-6eda-4b91-abd1-91a492b9e6ee",
            "sourceColumn": "Month No.",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "SWITCH([Month No.], 1, \"March\", 2, \"April\", 3, \"May\", 4, \"June\", 5, \"July\", 6, \"August\", 7, \"September\", 8, \"October\", 9, \"November\", 10, \"December\", 11, \"January\", 12, \"February\", \"Invalid Month\")",
            "isDataTypeInferred": true,
            "lineageTag": "e94a797b-3b8a-4a18-bc08-19a661cb5412",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Agency %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": "DIVIDE(vwAgencyCostPercOfTotalCost[AgencyCostPercOfTotalCost],100)",
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "14a17c01-0c96-474e-8ba4-7d2396d90334",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Fiscalyear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "be1b5c2a-7810-489e-ae47-d491b8620b15",
            "sourceColumn": "Fiscalyear",
            "summarizeBy": "sum"
          },
          {
            "name": "rm_hoa_fm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(vwAgencyCostPercOfTotalCost[Head of Operations],vwAgencyCostPercOfTotalCost[Regional Manager]),vwAgencyCostPercOfTotalCost[Period])",
            "isDataTypeInferred": true,
            "lineageTag": "4def20bb-d812-407a-af98-b3e3cd124053",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "TotalSatffCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "073bb84a-82b2-4c2c-9fb8-1e98ea614b4c",
            "sourceColumn": "TotalSatffCost",
            "summarizeBy": "sum"
          },
          {
            "name": "Service Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3caeee3f-b636-4e07-b4d2-b89fbbdc8519",
            "sourceColumn": "Service Status",
            "summarizeBy": "none"
          },
          {
            "name": "hoa_reg_fm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(vwAgencyCostPercOfTotalCost[Head of Operations],vwAgencyCostPercOfTotalCost[Region]),vwAgencyCostPercOfTotalCost[Period])",
            "isDataTypeInferred": true,
            "lineageTag": "2b0e9e64-77ed-4cb1-bcb2-a6062f6998ca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5eb625dd-08c3-40ef-b71c-e6babad86a6f",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Facility Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d25cd59-b9c7-4a2a-bd76-479d1aca9ef3",
            "sourceColumn": "Facility Code",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2cf444fe-b82e-4660-8d61-175874c57461",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "83dd468c-7324-448e-afaf-83e3d9e6dd4d",
        "measures": [
          {
            "name": "Agency_Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),Autumn_RMtargets,Autumn_RMtargets[Measure]=\"Agency reduction vs total staff costs\",Autumn_RMtargets[Regional Manager]<>\"rm\")",
            "lineageTag": "ad92ef17-bba7-40a1-aae9-527915cc808c"
          },
          {
            "name": "Avg Agency",
            "expression": "AVERAGE(vwAgencyCostPercOfTotalCost[AgencyCostPercOfTotalCost])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dc9ba4e1-c5da-41b6-bdcf-93254d8b4ade"
          },
          {
            "name": "Agencytarget",
            "expression": [
              "",
              "IF ( [Avg Agency] >[Agency_Target],0,1)"
            ],
            "formatString": "0.0000",
            "lineageTag": "d72d9c9c-567b-40b6-bb10-79beff71191a"
          },
          {
            "name": "Avg Agency %",
            "expression": [
              "",
              "var a = [Avg Agency]",
              "return IF(ISBLANK(a),0,a/100)",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ff0fa848-e273-4dad-a362-99be7c660278"
          }
        ],
        "partitions": [
          {
            "name": "vwAgencyCostPercOfTotalCost-a59dd110-3e31-45ba-9d55-82534f490b19",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqlminstanceatprod.public.6ebcd2a481ea.database.windows.net,3342\", \"ATDMP\"),",
                "    dbo_vwAgencyCostPercOfTotalCost = Source{[Schema=\"dbo\",Item=\"vwAgencyCostPercOfTotalCost\"]}[Data],",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(dbo_vwAgencyCostPercOfTotalCost, \"Period\", \"Period - Copy\"),",
                "    #\"Split Column by Position\" = Table.SplitColumn(Table.TransformColumnTypes(#\"Duplicated Column\", {{\"Period - Copy\", type text}}, \"en-US\"), \"Period - Copy\", Splitter.SplitTextByRepeatedLengths(4), {\"Period - Copy.1\", \"Period - Copy.2\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Split Column by Position\",{{\"Period - Copy.1\", Int64.Type}, {\"Period - Copy.2\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Period - Copy.1\", \"Year\"}, {\"Period - Copy.2\", \"Month No.\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Autumn_RMtargets",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Head Of Operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa93b816-3be5-4fda-9e28-5f066451907b",
            "sourceColumn": "Head Of Operations",
            "summarizeBy": "none"
          },
          {
            "name": "Regional Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc2f5f1e-1d81-4673-bcb9-5ba16759f5ab",
            "sourceColumn": "Regional Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dab001e0-a1f6-48b6-87af-8fb416a437c9",
            "sourceColumn": "Measure",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9fb94afc-308b-49ba-a681-4e659cd48e75",
            "sourceColumn": "FiscalYear",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "790d8e1c-28f6-49df-9370-2600d6624786",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "b40e18ee-63d3-497f-a900-e1fa3554e32d",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "518ca033-dfe1-40f7-b9c9-962fa32a8d97",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearMonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "CONCATENATE(Autumn_RMtargets[FiscalYear],",
              "SWITCH(Autumn_RMtargets[Month Name],",
              "\"March\",\t\"01\",",
              "\"April\",\t\"02\",",
              "\"May\",\t\"03\",",
              "\"June\",\t\"04\",",
              "\"July\",\t\"05\",",
              "\"August\",\t\"06\",",
              "\"September\",\t\"07\",",
              "\"October\",\t\"08\",",
              "\"November\",\t\"09\",",
              "\"December\",\t\"10\",",
              "\"January\",\t\"11\",",
              "\"February\",\t\"12\"))",
              "",
              "",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "265ee97d-dfae-454f-b0d9-15e7f0e9138b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Rm_HOA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(Autumn_RMtargets[Head Of Operations],Autumn_RMtargets[Regional Manager])",
            "isDataTypeInferred": true,
            "lineageTag": "425bbb4c-43a3-43a5-9826-7c19054f43f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "rm_hoa_fm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(Autumn_RMtargets[Head Of Operations],Autumn_RMtargets[Regional Manager]),Autumn_RMtargets[FiscalYearMonthNo])",
            "isDataTypeInferred": true,
            "lineageTag": "e5bcce8d-4f7f-45d2-88e6-5a49767128f8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "kateflag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF(Autumn_RMtargets[Head of Operations]=\"Kate Durband\",0,1)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9e2547aa-bbbb-490c-bc9d-05a82d54d092",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "hoa_reg_fm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(Autumn_RMtargets[Head Of Operations],Autumn_RMtargets[Region]),Autumn_RMtargets[FiscalYearMonthNo])",
            "isDataTypeInferred": true,
            "lineageTag": "c21c09fc-df39-45b6-93a2-5e8928df4873",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Operations Director",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40a55e19-04a9-4f50-a8dc-4a757c35c616",
            "sourceColumn": "Operations Director",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6c07320b-6e09-4392-b240-3d0ab102a462",
        "measures": [
          {
            "name": "AvgOccupancy",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM(Autumn_RMtargets[Value]),FILTER(Autumn_RMtargets,Autumn_RMtargets[Measure]=\"occupancy\" && Autumn_RMtargets[Regional Manager]=\"no rm\")",
              ")"
            ],
            "lineageTag": "c96437fc-7a6d-412e-b358-3776de8d53cb"
          },
          {
            "name": "AVG Good",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),FILTER(Autumn_RMtargets,Autumn_RMtargets[Measure]=\"Quality-Good\" && Autumn_RMtargets[Regional Manager]=\"no rm\")",
              ")"
            ],
            "lineageTag": "8fdd1899-545b-43cc-954f-fa6c7e4587e8"
          },
          {
            "name": "Avg RI",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),FILTER(Autumn_RMtargets,Autumn_RMtargets[Measure]=\"Quality-RI\" && Autumn_RMtargets[Regional Manager]=\"no rm\")",
              ")"
            ],
            "lineageTag": "fe8e4b0b-b646-413f-a776-edb16989adfe"
          },
          {
            "name": "Avg INadequate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),FILTER(Autumn_RMtargets,Autumn_RMtargets[Measure]=\"Quality-IN\" && Autumn_RMtargets[Regional Manager]=\"no rm\")",
              ")"
            ],
            "lineageTag": "42ad7dd5-dda8-450a-9586-eecc9fa5078b"
          },
          {
            "name": "Avg Staff churn",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),FILTER(Autumn_RMtargets,Autumn_RMtargets[Measure]=\"Staffing - retention\" && Autumn_RMtargets[Regional Manager]=\"no rm\")",
              ")"
            ],
            "lineageTag": "23668455-49f0-4f4b-8389-e0f5abb5e31a"
          },
          {
            "name": "AvgAgency",
            "expression": [
              "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),FILTER(Autumn_RMtargets,Autumn_RMtargets[Measure]=\"Agency reduction vs total staff costs\"), Autumn_RMtargets[Regional Manager]=\"no rm\")",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1515a1bb-0faf-42e2-9393-8703edda629b"
          },
          {
            "name": "Occupanci RM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(sum(Autumn_RMtargets[Value]),FILTER(Autumn_RMtargets,Autumn_RMtargets[Measure]=\"occupancy\" && Autumn_RMtargets[Regional Manager]<>\"no rm\"),Autumn_RMtargets[Month Name]=MAX(Autumn_RMtargets[Month Name])",
              ")"
            ],
            "lineageTag": "7d1e9024-9d67-417e-9edb-91c0da1fa158"
          },
          {
            "name": "Avg RI RM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),FILTER(Autumn_RMtargets,Autumn_RMtargets[Measure]=\"Quality-RI\" && Autumn_RMtargets[Regional Manager]<>\"no rm\")",
              ")"
            ],
            "lineageTag": "1eec1b42-85c2-46df-9ccd-5ee534164704"
          },
          {
            "name": "Target Good",
            "expression": [
              "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-Good\")",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "20a40e87-909c-4f0e-bffe-f74f8d3ac67f"
          },
          {
            "name": "Target Inadequate",
            "expression": "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-IN\")",
            "formatString": "0",
            "lineageTag": "0cc32ffb-cbae-4de6-bcb4-517367eaf986"
          },
          {
            "name": "Target RI",
            "expression": [
              "var a= CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-RI\")",
              "",
              "var b = DISTINCTCOUNT(VW_CQCUnratedLocationRatingDtls[Regulator ID])",
              "",
              "return a"
            ],
            "formatString": "0",
            "lineageTag": "63dc3cdc-9405-41bc-9a51-d5a430289d85"
          },
          {
            "name": "Target Occupancy",
            "expression": "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Occupancy\")",
            "formatString": "0",
            "lineageTag": "8c73a05d-4e3a-4b39-9339-c7bfab053577"
          },
          {
            "name": "Target Agency",
            "expression": [
              "",
              "",
              "var a  = CALCULATE(AVERAGE((Autumn_RMtargets[Value])),Autumn_RMtargets[Measure]=\"Agency reduction vs total staff costs\")",
              "--var b = CALCULATE(DISTINCTCOUNT(DimServiceLocationsMapping[Regulator ID]))",
              "",
              "return a",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "791e1049-e648-4d6e-ada9-4cb02bfb3e8e"
          },
          {
            "name": "No RM Inadequte",
            "expression": [
              "var a= CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-IN\",Autumn_RMtargets[Regional Manager]=\"no RM\")",
              "",
              "var b = DISTINCTCOUNT(VW_CQCUnratedLocationRatingDtls[Regulator ID])",
              "",
              "return a/b"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "bd7d7f2a-5fdb-4066-9648-188b974c2562"
          },
          {
            "name": "No RM Target Good",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM(Autumn_RMtargets[Value]),FILTER(Autumn_RMtargets,Autumn_RMtargets[Measure]=\"Quality-Good\"),Autumn_RMtargets[Regional Manager]=\"no rm\")",
              "",
              "--var b = DISTINCTCOUNT(VW_CQCUnratedLocationRatingDtls[Regulator ID])",
              "",
              "--return a/b"
            ],
            "formatString": "0",
            "lineageTag": "9c0471ad-899d-4332-aec2-9da8ae0ab418"
          },
          {
            "name": "No RMTarget RI",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-RI\",Autumn_RMtargets[Regional Manager]=\"no RM\")",
              "",
              "--var b = DISTINCTCOUNT(VW_CQCUnratedLocationRatingDtls[Regulator ID])",
              "",
              "--return a/b"
            ],
            "formatString": "0",
            "lineageTag": "d6dcc97f-dc78-4a77-a808-4ccb0c59e0fe"
          },
          {
            "name": "No RM Target Agency",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Agency reduction vs total staff costs\",Autumn_RMtargets[Regional Manager]=\"no rm\")",
              "",
              ""
            ],
            "lineageTag": "91fe25c9-3673-421b-bc57-bfcf06c8a6ad"
          },
          {
            "name": "No RMTarget Occupancy",
            "expression": [
              "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Occupancy\",Autumn_RMtargets[Regional Manager]=\"no rm\")",
              "",
              "--var b = DISTINCTCOUNT(DimServiceLocationsMapping[Regulator ID])",
              "",
              "--return a"
            ],
            "formatString": "0",
            "lineageTag": "f43e9d9a-8a9f-41cc-8325-e108faeecb38"
          },
          {
            "name": "Target flag  Good RM",
            "expression": "IF(ISBLANK([Quality]),2,if([Quality]>=[Target Good],0,1))",
            "formatString": "0",
            "lineageTag": "46afd55a-a6ba-4eb7-a77e-0c7a41035b0b"
          },
          {
            "name": "Target Flag RI RM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var tar = IF(ISBLANK([Target_RI_chart]), 0)",
              "return IF(ISBLANK([RI %]),2,IF([RI %]<=tar ,\"G\",\"R\"))"
            ],
            "lineageTag": "bfdf50ec-6fad-4b9d-a7ad-0a37fd7b0739"
          },
          {
            "name": "Target Flag IN RM",
            "expression": "IF(ISBLANK([Inadequate %]),2,IF([Inadequate %]>[Target Inadequate],0,1))",
            "formatString": "0",
            "lineageTag": "8c9ca05f-85a0-436d-b366-54d327853c84"
          },
          {
            "name": "Target Flag Occ RM",
            "expression": [
              "IF(ISBLANK([Max Occupancy]),2,IF([Max Occupancy]>=[Target Occupancy],0,1))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9767aafa-cf45-4eb7-9bb8-edaa8e6810d6"
          },
          {
            "name": "Target Flag Agency RM",
            "expression": "IF(ISBLANK([Avg Agency %]),2,IF(AVERAGE(vwAgencyCostPercOfTotalCost[Agency %])>=[Target Agency],0,1))",
            "formatString": "0",
            "lineageTag": "085187c3-f6f2-40d0-bdbe-f00a19f321a0"
          },
          {
            "name": "No Rm Good flag",
            "expression": "IF(ISBLANK([Quality]),2,IF([Quality]>[No RM Target Good],0,1))",
            "formatString": "0",
            "lineageTag": "d35ff9c4-ab9c-47d3-a0b6-bb74675efcd1"
          },
          {
            "name": "No RM RI flag",
            "expression": "IF(ISBLANK([RI %]),2,IF([Ri %]>[No RMTarget RI],0,1))",
            "formatString": "0",
            "lineageTag": "2813dd9f-9586-4c0e-b391-7c93936ed261"
          },
          {
            "name": "No Rm Inadeqate flag",
            "expression": "IF(ISBLANK([Inadequate %]),2,IF([Inadequate %]>[No RM Inadequte],0,1))",
            "formatString": "0",
            "lineageTag": "14c68320-efea-4809-b8be-c074478733b0"
          },
          {
            "name": "Target Good test",
            "expression": [
              "var a= CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-Good\",Autumn_RMtargets[Regional Manager]<>\"no rm\")",
              "",
              "var b = DISTINCTCOUNT(VW_CQCUnratedLocationRatingDtls[Regulator ID])",
              "",
              "return IF(ISBLANK(a),\" \",a/b)",
              "",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "3f3b55e5-a9ec-4209-a09f-41aa9b592bd2"
          },
          {
            "name": "Agency rm",
            "expression": [
              "CALCULATE(AVERAGE(Autumn_RMtargets[Value]),FILTER(Autumn_RMtargets,Autumn_RMtargets[Measure]=\"Agency reduction vs total staff costs\" && Autumn_RMtargets[Regional Manager]<>\"no rm\")",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "722fedf3-d629-442e-a379-0b6013571db0"
          },
          {
            "name": "No RM Target Outstanding",
            "expression": [
              "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Outstanding\",Autumn_RMtargets[Regional Manager]=\"rm\")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d9fca83d-5ae6-4405-87da-4008b5f82638"
          },
          {
            "name": "Target Outstanding",
            "expression": [
              "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-Outstanding\")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "2cca0b46-3099-4ec1-b05d-99faca7d12c0"
          },
          {
            "name": "No Rm Outstanding flag",
            "expression": [
              "--var a = IF(ISBLANK([Outstanding]),2,IF([Outstanding]>[No RM Target Outstanding],0,1))",
              "",
              "var a =CALCULATE(SUM(Autumn_RMtargets[kateflag]))",
              "",
              "return IF(a<1,3,IF(ISBLANK([Outstanding]),2,IF([Outstanding]>[No RM Target Outstanding],0,1)))",
              "",
              "--return b"
            ],
            "formatString": "0",
            "lineageTag": "bfa18562-767f-4cb4-877c-93cdb443cfb3"
          },
          {
            "name": "Target Outstanding flag",
            "expression": [
              "--IF(ISBLANK([Outstanding]),2,IF([Outstanding]>[Target Outstanding],0,1))",
              "",
              "var a =CALCULATE(SUM(Autumn_RMtargets[kateflag]))",
              "",
              "return IF(a<1,3,IF(ISBLANK([Outstanding]),2,IF([Outstanding]>=[Target Outstanding],1,0)))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "e5fae44e-ae56-47f3-a883-3e9065fb16c0"
          },
          {
            "name": "sum",
            "expression": "CALCULATE(SUM(DimServiceLocationsMapping[Column]),DimServiceLocationsMapping[Head of Operations]=\"kate durband\")",
            "formatString": "0",
            "lineageTag": "ddec7a78-98aa-435b-a3c3-7c287aa8cb6d"
          },
          {
            "name": "Target_Occupancy_chart",
            "expression": "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Occupancy\", Autumn_RMtargets[Regional Manager]<>\"rm\")",
            "formatString": "0",
            "lineageTag": "0c1191fb-143c-461c-92ea-c4dff40e1b7b"
          },
          {
            "name": "Target_Good_Chart",
            "expression": "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-Good\",Autumn_RMtargets[Regional Manager]<>\"no rm\")",
            "formatString": "0",
            "lineageTag": "bd1bd1cb-7c7c-4edc-bf63-a21e30f0739f"
          },
          {
            "name": "Target_RI_chart",
            "expression": "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-RI\")",
            "formatString": "0",
            "lineageTag": "ad7f38a9-2b1e-4032-be32-2e609e5f821e"
          },
          {
            "name": "Target_Inadequate_chart",
            "expression": "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-IN\")",
            "formatString": "0",
            "lineageTag": "ffbc8f9a-a623-4efa-8ee0-8310d689d18e"
          },
          {
            "name": "Target_Agency_chart",
            "expression": [
              "",
              "",
              "var a = CALCULATE(AVERAGE(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Agency reduction vs total staff costs\")",
              "",
              "--var b = CALCULATE(DISTINCTCOUNT(DimServiceLocationsMapping[Regulator ID]))",
              "",
              "--return IF(a=0 || b=0,0,a/b)",
              "",
              "return a",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "02cf1ad2-76de-4bd0-9e7e-e7a0911e1f23"
          },
          {
            "name": "Target_Outstanding_chart",
            "expression": [
              "",
              "",
              "var a = CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-Outstanding\")",
              "return a",
              "--return if(ISBLANK(a),0, a)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "90b1d8b4-84d9-4bd1-9809-1962e95aaab4"
          },
          {
            "name": "Target Flag RI RM_Hoa",
            "expression": [
              "",
              "var tar = IF(ISBLANK([Target RI]),0)",
              "return IF(ISBLANK([RI %]),2,IF([RI %]>[Target RI],0,1))"
            ],
            "formatString": "0",
            "lineageTag": "3a7846bf-3382-41e6-b73d-3fcadca37922"
          },
          {
            "name": "Target Occupancy Axis",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Occupancy\")/10",
            "lineageTag": "5c633053-d8ce-49ec-b8b2-0b3746ea20cc"
          },
          {
            "name": "Target Good Axis",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-Good\")/10",
              "",
              ""
            ],
            "lineageTag": "7a8958b2-3092-41ad-9769-4537bb974974"
          },
          {
            "name": "Target Outstanding Axis",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(SUM(Autumn_RMtargets[Value]),Autumn_RMtargets[Measure]=\"Quality-Outstanding\")/2",
              ""
            ],
            "lineageTag": "380d0e09-e822-4023-86da-47b2fddd696c"
          }
        ],
        "partitions": [
          {
            "name": "Autumn_RMtargets-ccefe88e-0869-46d0-afee-eab188612619",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"sqlminstanceatprod.public.6ebcd2a481ea.database.windows.net,3342\", \"ATDMP\", [Query=\"select distinct case when A.[Operations Director] is null and A.[Head of Operations] = 'Dean Thomas-Bines (he/him)'#(lf)then 'Victoria Hodgson' else A.[Operations Director] end as [Operations Director],B.* from dbo.DimServiceLocationsMapping A#(lf)JOIN dbo.Autumn_RMTargets B on A.[Head of Operations] = B.[Head Of Operations] #(lf)and isnull(A.[Regional Manager], 'Vacant') = B.[Regional Manager]#(lf)and A.Region = B.Region#(lf)where [Service Status] in ('Pending','New','Open')\"]),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(Source,{{\"FiscalYear\", Int64.Type}}),",
                "    Custom1 = Table.Unpivot(#\"Changed Type2\", {\"March\", \"April\", \"May\", \"June\", \"July\", \"August\", \"September\", \"October\", \"November\", \"December\", \"January\", \"February\"}, \"Attribute\", \"Value\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Custom1,{{\"Value\", type number}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",null,\"no rm\",Replacer.ReplaceValue,{\"Regional Manager\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Replaced Value\",{{\"Attribute\", \"Month Name\"}}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Renamed Columns\",\"Dean Thomas-Bines (he/him)\",\"Dean Thomas-Bines\",Replacer.ReplaceText,{\"Head Of Operations\"})",
                "in",
                "    #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_83d935b1-9980-4b2a-9f55-8be80245df33",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "070e67aa-0587-4bb8-a6f0-78cf712c1d7a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "17b2d80a-949b-4a82-bef5-279f2a84fd92",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8651a3c2-af3f-4429-8b91-8671fcd5205d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fa77fc5d-8327-4d2c-b38b-87036c46f9f5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "93575866-c4ea-4d16-8919-f7363520d591",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3a84fbac-788b-42e8-bd8c-a909c4da33ab",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3fcd92d5-fb6e-4caa-9ec6-70bb717b2a7b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ac22ebfe-7fa5-43bf-8280-4515daf6ebb4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c677569b-84b0-45fd-b69f-c45f0f8d6b2a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9d112b67-bc19-41b1-b795-954e0aa99749",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "83dbad74-9b63-4917-a4d6-85681479aa52",
                "ordinal": 3
              }
            ],
            "lineageTag": "44e92269-4758-4f72-bf13-8e8723aaa444"
          }
        ],
        "isHidden": true,
        "lineageTag": "0579cbcc-8eb3-4a64-86f4-4d92282fb51a",
        "partitions": [
          {
            "name": "LocalDateTable_83d935b1-9980-4b2a-9f55-8be80245df33-3f64e12f-098f-443d-bfb9-3c9fc33e03a2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('vwOccupancyRate'[Empty_Dt])), 1, 1), Date(Year(MAX('vwOccupancyRate'[Empty_Dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "VW_CQCLocationRatingDtls",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbece818-6de0-4614-8d15-b5f41eda852b",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Property interest",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4b8f73b-12f7-4ac4-acd9-30c0563204f3",
            "sourceColumn": "Property interest",
            "summarizeBy": "none"
          },
          {
            "name": "Facility Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e399596-e3c8-435a-bf18-16ea24b9e210",
            "sourceColumn": "Facility Status",
            "summarizeBy": "none"
          },
          {
            "name": "Service Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "292f66a6-e222-47cb-9b70-2f55420cb2a2",
            "sourceColumn": "Service Status",
            "summarizeBy": "none"
          },
          {
            "name": "Service Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ddf2e06-d6e0-4ad0-8398-9e3aac180cba",
            "sourceColumn": "Service Type",
            "summarizeBy": "none"
          },
          {
            "name": "Agency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30b9e5ef-e013-4c9e-a4ba-46a5fc365e8a",
            "sourceColumn": "Agency",
            "summarizeBy": "none"
          },
          {
            "name": "Regulator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb306ff1-0d4d-4ff3-8ab0-597333cc2aa7",
            "sourceColumn": "Regulator",
            "summarizeBy": "none"
          },
          {
            "name": "Regulator ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d405ecdf-c115-4741-a4aa-a21a14c862e4",
            "sourceColumn": "Regulator ID",
            "summarizeBy": "none"
          },
          {
            "name": "Regulator Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d7386d7-1cbc-443f-9902-2eeb692ab7b2",
            "sourceColumn": "Regulator Name",
            "summarizeBy": "none"
          },
          {
            "name": "Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2eabdd82-038c-464e-bb45-618d9bc34065",
            "sourceColumn": "Area",
            "summarizeBy": "none"
          },
          {
            "name": "Operations Director",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "351f1f3a-1af8-4b3c-ae01-04e2b76a3b96",
            "sourceColumn": "Operations Director",
            "summarizeBy": "none"
          },
          {
            "name": "Head of Operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ee3f753-98e9-48ee-a8e7-a6022fb366f7",
            "sourceColumn": "Head of Operations",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfa80a02-7286-41bc-aaba-176cd46296a5",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Regional Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dab84075-3dbc-454b-af99-6dd34452bafe",
            "sourceColumn": "Regional Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Senior Service Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1998913-0987-4e60-9a19-0a6958d9d7fe",
            "sourceColumn": "Senior Service Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b8bb38e-19fa-483d-94df-8a41ffc45f21",
            "sourceColumn": "Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Deputy Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da8b4246-3537-44c4-b503-68ecd94705de",
            "sourceColumn": "Deputy Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Administrator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81455e92-9bd3-4642-87c0-9d43de75deb3",
            "sourceColumn": "Administrator",
            "summarizeBy": "none"
          },
          {
            "name": "Recruitment Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1027d511-852d-48f6-b699-e6db8717a463",
            "sourceColumn": "Recruitment Manager",
            "summarizeBy": "none"
          },
          {
            "name": "HR Advisor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74ff48ca-458c-4d3c-a3db-f07ed125799a",
            "sourceColumn": "HR Advisor",
            "summarizeBy": "none"
          },
          {
            "name": "APM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18193721-47b4-4404-a3ff-e5e8cc50b704",
            "sourceColumn": "APM",
            "summarizeBy": "none"
          },
          {
            "name": "Quality Partner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef7659e2-1af0-4ebe-a089-a8f922f32469",
            "sourceColumn": "Quality Partner",
            "summarizeBy": "none"
          },
          {
            "name": "Local Authority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba2e93a1-1995-4058-bea7-76f5301cb9d8",
            "sourceColumn": "Local Authority",
            "summarizeBy": "none"
          },
          {
            "name": "Phone Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea1d20ba-614c-4fd9-bb46-8b8998306ae5",
            "sourceColumn": "Phone Number",
            "summarizeBy": "none"
          },
          {
            "name": "Cost Centre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53740664-198e-4abb-845e-de876e29b946",
            "sourceColumn": "Cost Centre",
            "summarizeBy": "none"
          },
          {
            "name": "Facility Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac515d22-457d-4f78-8234-ac14590c47b2",
            "sourceColumn": "Facility Code",
            "summarizeBy": "none"
          },
          {
            "name": "Historical Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9fd618cf-8cab-40f3-b135-7cadd069a806",
            "sourceColumn": "Historical Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Update Required?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e35d7151-1c4d-47a5-b324-88be288ae429",
            "sourceColumn": "Update Required?",
            "summarizeBy": "none"
          },
          {
            "name": "Temporary Systems Access Request",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40611d2e-7295-47c9-a32b-54c83786da9a",
            "sourceColumn": "Temporary Systems Access Request",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3a2ac4de-3d84-400f-9005-4d94fc859794",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "Modified",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "befdd4cf-605e-48f7-bb60-b9f19119b0b3",
            "sourceColumn": "Modified",
            "summarizeBy": "none"
          },
          {
            "name": "Modified By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ab6f3f6-8acc-487d-8d3e-0ffad8e1a1ca",
            "sourceColumn": "Modified By",
            "summarizeBy": "none"
          },
          {
            "name": "R1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc64c36e-a17c-46c3-b1db-c05ff0b40981",
            "sourceColumn": "R1",
            "summarizeBy": "none"
          },
          {
            "name": "AC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "364c0d91-308a-48ae-9abe-7f630ff4cc59",
            "sourceColumn": "AC",
            "summarizeBy": "none"
          },
          {
            "name": "HC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cfebaae-9795-4ea8-b7a6-042eaf1c1e18",
            "sourceColumn": "HC",
            "summarizeBy": "none"
          },
          {
            "name": "OfficeSpace",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c34ecca8-9b7e-4cae-ba7f-d4ac21d28337",
            "sourceColumn": "OfficeSpace",
            "summarizeBy": "none"
          },
          {
            "name": "LocationCountryRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "582fb0f5-73bd-4ba6-a9cd-dc43d8078b15",
            "sourceColumn": "LocationCountryRegion",
            "summarizeBy": "none"
          },
          {
            "name": "Coordinates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65a28aab-b9ac-49f6-bf3d-5ad7da0bb1d1",
            "sourceColumn": "Coordinates",
            "summarizeBy": "none"
          },
          {
            "name": "Map_LocationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "135890c0-9166-4da1-bba6-e2763ae7748b",
            "sourceColumn": "Map_LocationName",
            "summarizeBy": "none"
          },
          {
            "name": "Map_Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84e5251d-7e8c-438e-aa87-48680dc0e318",
            "sourceColumn": "Map_Country",
            "summarizeBy": "none"
          },
          {
            "name": "Map_City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9fff34eb-9ef7-4f6a-98b1-6b959f6a1914",
            "sourceColumn": "Map_City",
            "summarizeBy": "none"
          },
          {
            "name": "Map_PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "143048db-6f6e-4b01-b6fc-a58643a0dbd5",
            "sourceColumn": "Map_PostalCode",
            "summarizeBy": "none"
          },
          {
            "name": "Map_Street",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7796736-a69e-4b06-b346-34417eb290fe",
            "sourceColumn": "Map_Street",
            "summarizeBy": "none"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f72c9e0-695d-4181-84a7-e3973943a7d4",
            "sourceColumn": "Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1af15a38-d8af-465a-ab0c-ddf8dd4f898b",
            "sourceColumn": "Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Service_population_group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c89a6672-ed21-4501-8ee2-b25801ce1eef",
            "sourceColumn": "Service_population_group",
            "summarizeBy": "none"
          },
          {
            "name": "Domain",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efaa7aea-290b-4341-987b-0028f8ec7a12",
            "sourceColumn": "Domain",
            "summarizeBy": "none"
          },
          {
            "name": "CQCLatestRatings",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4551c054-23d4-482d-a3c3-4972a4bf2f9b",
            "sourceColumn": "CQCLatestRatings",
            "summarizeBy": "none"
          },
          {
            "name": "Publication_Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4fa0b348-ecd9-4664-8b4e-edd74e218a66",
            "sourceColumn": "Publication_Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_62cae5d2-bf80-4cb7-ac76-c0cb73bfc310"
                },
                "isDefault": true,
                "relationship": "9aa9bcf6-f059-4781-9468-f5fb6ad98ed0"
              }
            ]
          },
          {
            "name": "DraftReportDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5c06379b-17b4-401a-a019-7a16c22263ff",
            "sourceColumn": "DraftReportDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_639f3697-e557-4885-bea0-cff7367d1e93"
                },
                "isDefault": true,
                "relationship": "db832b54-3acf-475c-ae7f-788eb7ce2d1f"
              }
            ]
          },
          {
            "name": "DraftRating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99f4eafb-b0e4-4aae-93b1-900b1bbbd528",
            "sourceColumn": "DraftRating",
            "summarizeBy": "none"
          },
          {
            "name": "Report_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab1489bb-6ce7-4709-91ca-aaa20ddec41b",
            "sourceColumn": "Report_Type",
            "summarizeBy": "none"
          },
          {
            "name": "Inherited_Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a98eeef6-a8c4-4e1f-8849-ec44e77f3321",
            "sourceColumn": "Inherited_Rating",
            "summarizeBy": "none"
          },
          {
            "name": "Report_Url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4765bf40-4c4b-4160-9a42-88e322e3d197",
            "sourceColumn": "Report_Url",
            "summarizeBy": "none"
          },
          {
            "name": "Manual_Override_ratings",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11556782-cffc-4b37-b6c5-563e6fb798aa",
            "sourceColumn": "Manual_Override_ratings",
            "summarizeBy": "none"
          },
          {
            "name": "Operation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d06def3-8937-4ff9-abd4-317d720b1a00",
            "sourceColumn": "Operation",
            "summarizeBy": "none"
          },
          {
            "name": "Reason_For_Adjustment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b74201f8-0557-411b-a6b8-cbfe59ca15cc",
            "sourceColumn": "Reason_For_Adjustment",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal_Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "89d2ab38-fbd9-473b-a8f9-15df5db6e3a4",
            "sourceColumn": "Fiscal_Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Latest_Audit_Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f201c58-c8e5-43ca-aad7-b99c3ac58f7c",
            "sourceColumn": "Latest_Audit_Rating",
            "summarizeBy": "none"
          },
          {
            "name": "Overdue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca821456-565b-45b0-aa1b-4f378781f661",
            "sourceColumn": "Overdue",
            "summarizeBy": "sum"
          },
          {
            "name": "SourceFilename",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6da1b13-4c41-44cf-915f-c974f34b082f",
            "sourceColumn": "SourceFilename",
            "summarizeBy": "none"
          },
          {
            "name": "hoa_rm_fm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(VW_CQCLocationRatingDtls[Head of Operations],VW_CQCLocationRatingDtls[Regional Manager]),VW_CQCLocationRatingDtls[Fiscal_Month]) ",
            "isDataTypeInferred": true,
            "lineageTag": "899353a6-e96c-414f-8741-08a1f7b6192c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "hoa_reg_fm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(VW_CQCLocationRatingDtls[Head of Operations],VW_CQCLocationRatingDtls[Region]),VW_CQCLocationRatingDtls[Fiscal_Month]) ",
            "isDataTypeInferred": true,
            "lineageTag": "510d4529-25e4-4688-a398-8873d32284cf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "RI_Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]), VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"Requires improvement\")",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b1190535-75ef-4f0a-90d2-2cb6f3c66d62",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "IsVisitedThisMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f99fd8cd-7b39-4cfc-a606-0343308ba15b",
            "sourceColumn": "IsVisitedThisMonth",
            "summarizeBy": "none"
          },
          {
            "name": "Brand_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cc8cd97-ad40-4332-bc33-20c43c03b0ea",
            "sourceColumn": "Brand_Name",
            "summarizeBy": "none"
          },
          {
            "name": "ProviderName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1d9d3f4-2cfe-42f6-b50e-27b38cf263cb",
            "sourceColumn": "ProviderName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "94e89a8d-24fe-4d9c-ad99-eaa5f772f77b",
        "measures": [
          {
            "name": "%Count of Facility",
            "expression": "DISTINCTCOUNT(VW_CQCLocationRatingDtls[Facility Code])/COUNTA(VW_CQCLocationRatingDtls[Facility Code])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a165d0d9-cc79-4085-987e-771dcf32e537"
          },
          {
            "name": "Audit_rating",
            "expression": "DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]) ",
            "formatString": "0",
            "lineageTag": "51952606-b6ef-4859-81d5-784f076a2784"
          },
          {
            "name": "Outstanding_Chart",
            "expression": [
              "",
              "",
              "var act = CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),FILTER(VW_CQCLocationRatingDtls,VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"outstanding\"))",
              "",
              "return act"
            ],
            "formatString": "0",
            "lineageTag": "584ce3bb-f354-46ff-9e60-7d8858978bc8"
          },
          {
            "name": "Quality_Chart",
            "expression": "CALCULATE(DISTINCTCOUNT(VW_CQCLocationRatingDtls[Regulator ID]),FILTER(VW_CQCLocationRatingDtls,VW_CQCLocationRatingDtls[Manual_Override_ratings]=\"Good\"))",
            "formatString": "0",
            "lineageTag": "07e9340f-21bf-4eed-8122-7ce61b3b6da1"
          }
        ],
        "partitions": [
          {
            "name": "VW_CQCLocationRatingDtls-97ded7dd-6a11-41bf-8e1c-b4b57ae33360",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"sqlminstanceatprod.public.6ebcd2a481ea.database.windows.net,3342\"),",
                "    ATDMP = Source{[Name=\"ATDMP\"]}[Data],",
                "    dbo_VW_CQCLocationRatingDtls = ATDMP{[Schema=\"dbo\",Item=\"VW_CQCLocationRatingDtls\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(dbo_VW_CQCLocationRatingDtls,\"Dean Thomas-Bines (he/him)\",\"Dean Thomas-Bines\",Replacer.ReplaceText,{\"Head of Operations\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Replaced Value\", each ([Service Status] <> \"Closed\" and [Service Status] <> \"Closing/Repositioning\") and ([Domain] = \"Overall\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_62cae5d2-bf80-4cb7-ac76-c0cb73bfc310",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cce68306-b924-4c01-9972-557908fedab1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "23a804dd-0377-4125-96b2-bd970577eb90",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0d26929f-57ed-42f6-8243-55731fa0ef36",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b16cd932-bbfb-418f-9525-ef2641229e6c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "55c83f73-739b-41f7-9cbc-401f6b284469",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5736ced9-7bbb-4f54-badf-d7f48fd04b53",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "76a5c08b-3755-4f5a-b054-81a7e59a7a66",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5d0b3a03-4060-4cdb-8583-617fc260d416",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3681510f-1da8-446c-b1a6-0a08efd32b19",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "930fe0fb-53cb-4e7f-bba1-8af390def832",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e67bbb4a-fcfc-4a03-967c-82ec725fe0ee",
                "ordinal": 3
              }
            ],
            "lineageTag": "fe7e40e1-f4ed-4cb0-aa01-4b3c35a1118e"
          }
        ],
        "isHidden": true,
        "lineageTag": "dc89ad3a-f647-41b1-8592-415e85ab3427",
        "partitions": [
          {
            "name": "LocalDateTable_62cae5d2-bf80-4cb7-ac76-c0cb73bfc310-b649b261-85d4-4b00-afd1-d376d8a251fe",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('VW_CQCLocationRatingDtls'[Publication_Date])), 1, 1), Date(Year(MAX('VW_CQCLocationRatingDtls'[Publication_Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_639f3697-e557-4885-bea0-cff7367d1e93",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f0712b04-ff3d-477a-8b54-cf885091dd21",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3b02f2d2-9d67-42c8-b84d-9f11fd4d7448",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9beb51a8-8f92-47cb-a9a2-27276955fd35",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1502d128-3f84-434c-9362-f43d212966ce",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ed7286be-dd27-49a8-8d9b-93a1f2827c9c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c975c33f-84bb-4a7f-b9f0-b6037eb8011e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3373dbaf-06c4-46fc-b5b0-9ec765948474",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9ebbeb3f-0408-44dd-93cf-e4a64f5c465f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "38417f07-1a89-4da3-bee6-a95d4e0a899f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5abfcf66-3e30-4c3f-80bd-fdcd4f93f449",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "929c5d09-f5a5-4f0c-83a0-37e64f3fc77a",
                "ordinal": 3
              }
            ],
            "lineageTag": "fec76c6f-ddb1-4d58-b960-49de207547bf"
          }
        ],
        "isHidden": true,
        "lineageTag": "c0b6bd36-f7ba-4ce9-8191-c730150c99e3",
        "partitions": [
          {
            "name": "LocalDateTable_639f3697-e557-4885-bea0-cff7367d1e93-414daa60-4961-4337-89ac-1441037db496",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('VW_CQCLocationRatingDtls'[DraftReportDate])), 1, 1), Date(Year(MAX('VW_CQCLocationRatingDtls'[DraftReportDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "DatesTable",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a73c63139f994caa9ac84432a395b066"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "405b5cd9-832a-4dac-823b-9509cea0777b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Calendar Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM(DatesTable[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c83bff7b-2860-4a71-8bf3-5ba087b1e0bd",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Calendar Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "FORMAT(DATE(1, DatesTable[Calendar Month Number], 1), \"MMMM\")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "055fec7a-54ea-4894-8aa8-d435f8cb8034",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR(DatesTable[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "31ab3b04-1d6f-432b-9f65-9715a494d1ea",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR _FiscalMonthStart = 3",
              "RETURN",
              "    IF (",
              "        DatesTable[Calendar Month Number] >= _FiscalMonthStart,",
              "        DatesTable[Calendar Year] + 1,",
              "        DatesTable[Calendar Year]",
              "    )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2285aed0-eaeb-4c35-a06a-68bbf27b5285",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(DatesTable[Calendar Month Name],",
              "\"March\",\t\"01\",",
              "\"April\",\t\"02\",",
              "\"May\",\t\"03\",",
              "\"June\",\t\"04\",",
              "\"July\",\t\"05\",",
              "\"August\",\t\"06\",",
              "\"September\",\t\"07\",",
              "\"October\",\t\"08\",",
              "\"November\",\t\"09\",",
              "\"December\",\t\"10\",",
              "\"January\",\t\"11\",",
              "\"February\",\t\"12\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3ab18f34-c0a2-44e6-8ef2-d4e94d79bb2f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Calendar Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH(DatesTable[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "39ab7f18-0278-4fc0-b522-c66d3ea0dbe4",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "FiscalMonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(DatesTable[Fiscal Year],DatesTable[Fiscal Month]) ",
            "isDataTypeInferred": true,
            "lineageTag": "062c5830-a804-4bb2-95de-1e338331f9b5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "mon_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(DatesTable[Date],\"MMM-YY\")",
            "isDataTypeInferred": true,
            "lineageTag": "460e8921-799b-4785-aae1-bddc9b9ea355",
            "sortByColumn": "Fiscal Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "iscurrentmonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "var exst_year_mnth = MONTH(DatesTable[Date])",
              "var this_year_mnth = MONTH(now())",
              "",
              "return IF(exst_year_mnth = this_year_mnth, \"Yes\",\"No\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "01900abe-ac91-4e27-bace-9290e7b6bd5f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Calendar Year MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(DatesTable[Date],\"MMMM-YYYY\")",
            "isDataTypeInferred": true,
            "lineageTag": "c52d9eac-dc2e-4f09-91f0-25d9f45b7bcb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Cal_Year_MonNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "CONVERT(FORMAT(DatesTable[Date],\"YYYYMM\"),INTEGER)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ee125d10-b66f-4d5c-a812-56249235662d",
            "sortByColumn": "FiscalMonthYear",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "645a7d19-6d8c-4d36-84d2-0c541e513e47",
        "measures": [
          {
            "name": "Current Month",
            "expression": [
              "IF(",
              "MONTH('D",
              "//     IF(",
              "//     MONTH('datesTable) = MONTH(TODAY()) && YEAR('VW_Reporting_Calendar'[Date]) = YEAR(TODAY()),",
              "//     1,",
              "//     0",
              "// ))"
            ],
            "lineageTag": "e4f224be-e0b5-4772-b319-63b9f694b78f"
          }
        ],
        "partitions": [
          {
            "name": "DatesTable-720b70ff-33f9-46d7-8c8a-94615657e853",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(DATE (2020, 1, 1), DATE (2030, 12, 31))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}